export const ROUTES = {
  home: '/',
  dashboard: '/dashboard',
  products: '/products',
  productNew: '/products/new',
  productEdit: (id: string) => `/products/${id}/edit`,
  masterProducts: '/master-products',
  masterProductNew: '/master-products/new',
  masterProductEdit: (id: string) => `/master-products/${id}/edit`,
  listedProductDetail: (id: string) => `/listed-products/${id}`,
  skus: '/skus',
  skuNew: '/skus/new',
  skuEdit: (id: string) => `/skus/${id}/edit`,
  salesProducts: '/sales-products',
  items: '/items',
  itemEdit: (itemCode: string) => `/items/${itemCode}/edit`,
  payments: '/orders/payments',
  newOrders: '/orders/new-orders',
  dispatch: '/dispatch',
  shipping: '/shipping',
  allOrders: '/all-orders',
  claims: '/claims',
  inventory: '/inventory',
  adminWarehouses: {
    connections: '/admin/warehouses',
    inbound: '/admin/warehouses/inbound',
    inventory: '/admin/warehouses/inventory',
    adjustments: '/admin/warehouses/adjustments',
    history: '/admin/warehouses/history',
    locations: '/admin/warehouses/locations',
  },
  inquiry: '/inquiry',
  externalSellers: '/external-sellers',
  settings: {
    channels: '/settings/channels',
    orders: '/settings/orders',
  },
  auth: {
    login: '/login',
    signup: '/signup',
  },
} as const;
